TebLocalPlannerROS:
  odom_topic: odometry/filtered
  map_frame: odom

  # Trajectory
  teb_autosize: true
  dt_ref: 0.3
  dt_hysteresis: 0.1
  max_samples: 500

  # Robot
  max_vel_x: 0.5
  max_vel_x_backwards: 0.3
  max_vel_theta: 1.0
  acc_lim_x: 0.8
  acc_lim_theta: 1.5
  is_footprint_dynamic: false
  footprint_model:
    type: "circular"
    radius: 0.25

  # Goal Tolerance
  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.1
  free_goal_vel: false

  # Obstáculos
  min_obstacle_dist: 0.5
  inflation_dist: 0.8
  include_costmap_obstacles: true
  costmap_obstacles_behind_robot_dist: 2.0
  obstacle_poses_affected: 30
  dynamic_obstacle_inflation_dist: 0.6
  weight_obstacle: 100
  
  # Optimización
  no_inner_iterations: 5
  no_outer_iterations: 4
  optimization_activate: true
  optimization_verbose: false
  penalty_epsilon: 0.1
  weight_max_vel_x: 2
  weight_max_vel_theta: 1
  weight_acc_lim_x: 1
  weight_acc_lim_theta: 1
  weight_kinematics_nh: 1000
  weight_kinematics_forward_drive: 0.5
  weight_kinematics_turning_radius: 0
  weight_goal_orientation: 1
  weight_obstacle: 50
  weight_viapoint: 1
  weight_dynamic_obstacle: 10
  weight_adapt_factor: 2

  # Preferencia de avance/retroceso
  prefer_forward_drive: false

  # Recovery
  shrink_horizon_backup: true
  shrink_horizon_min_duration: 10.0

  # Ajustes adicionales de planificación
  max_global_plan_lookahead_dist: 2.0
  feasibility_check_no_poses: 50
  recovery_min_reset_dist: 0.3
